name: shivaydairy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  flutter_zoom_drawer: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/allassets/  
